config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/inab/oeb_general_docs:
      branch: master
      repo: https://github.com/inab/oeb_general_docs
    github.com/inab/openEbench-frontend:
      branch: master
      repo: https://github.com/inab/openEbench-frontend
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/inab/openEbench-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-plum-urchin.sh
        container: qc.acc_chewy-bronze-civet
  QC.Doc:
    repos:
      github.com/inab/oeb_general_docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-aquamarine-ragdoll.sh
        container: qc.doc_snippy-russet-lobster
      github.com/inab/oeb_general_docs git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-firebrick-argentino.sh
        container: qc.doc_slaphappy-mauve-cuttlefish
      github.com/inab/oeb_general_docs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-brass-paradise.sh
        container: qc.doc_blurry-plum-tapir
      github.com/inab/oeb_general_docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-ochre-capuchin.sh
        container: qc.doc_slaphappy-mauve-squirt
  QC.Lic:
    repos:
      github.com/inab/openEbench-frontend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-green-wallaby.sh
        container: qc.lic_bumpy-flax-macaw
  QC.Ver:
    repos:
      github.com/inab/openEbench-frontend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-dandelion-crab.sh
        container: qc.ver_surly-periwinkle-hare
timeout: 1800
