config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/inab/openEbench-frontend:
      branch: master
      repo: https://github.com/inab/openEbench-frontend
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/inab/openEbench-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-ecru-chipmunk.sh
        container: qc.acc_pokey-orange-crab
  QC.Doc:
    repos:
      github.com/inab/openEbench-frontend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-brown-ant.sh
        container: qc.doc_pasty-wheat-rhinoceros
      github.com/inab/openEbench-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-jade-gharial.sh
        container: qc.doc_shaggy-rust-cow
      github.com/inab/openEbench-frontend markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-plum-grasshopper.sh
        container: qc.doc_lumpy-lemon-baboon
  QC.Lic:
    repos:
      github.com/inab/openEbench-frontend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-salmon-jellyfish.sh
        container: qc.lic_lumpy-zucchini-wolf
  QC.Sty:
    repos:
      github.com/inab/openEbench-frontend hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-turquoise-mammoth.sh
        container: qc.sty_paltry-ultramarine-echidna
      github.com/inab/openEbench-frontend jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-violet-cockroach.sh
        container: qc.sty_silly-celadon-duck
      github.com/inab/openEbench-frontend stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-teal-balinese.sh
        container: qc.sty_greasy-burgundy-cougar
  QC.Ver:
    repos:
      github.com/inab/openEbench-frontend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-celadon-dane.sh
        container: qc.ver_blurry-taupe-bison
timeout: 1800
