config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/inab/openEbench-frontend:
      branch: master
      repo: https://github.com/inab/openEbench-frontend
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/inab/openEbench-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-amber-leopard.sh
        container: qc.acc_sloppy-aquamarine-crab
  QC.Doc:
    repos:
      github.com/inab/openEbench-frontend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-cinnabar-macaw.sh
        container: qc.doc_chewy-alizarin-llama
      github.com/inab/openEbench-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-eggplant-tetra.sh
        container: qc.doc_seedy-ruby-hare
      github.com/inab/openEbench-frontend markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-magenta-molly.sh
        container: qc.doc_wheezy-alizarin-lizard
  QC.Lic:
    repos:
      github.com/inab/openEbench-frontend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-charcoal-stoat.sh
        container: qc.lic_flaky-orange-mule
  QC.Sty:
    repos:
      github.com/inab/openEbench-frontend hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-razzmatazz-bandicoot.sh
        container: qc.sty_snippy-cobalt-seal
      github.com/inab/openEbench-frontend jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-vermilion-kingfisher.sh
        container: qc.sty_sleazy-corn-okapi
      github.com/inab/openEbench-frontend stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-amaranth-heron.sh
        container: qc.sty_cheeky-corn-bison
  QC.Ver:
    repos:
      github.com/inab/openEbench-frontend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-cyan-tarsier.sh
        container: qc.ver_trippy-amber-mouse
timeout: 1800
