config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/inab/openEbench-frontend:
      branch: master
      repo: https://github.com/inab/openEbench-frontend
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/inab/openEbench-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-scarlet-whale.sh
        container: qc.acc_crappy-silver-buffalo
  QC.Doc:
    repos:
      github.com/inab/openEbench-frontend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-grey-butterfly.sh
        container: qc.doc_shabby-aqua-mule
      github.com/inab/openEbench-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-orchid-gerbil.sh
        container: qc.doc_snappy-burgundy-dane
      github.com/inab/openEbench-frontend markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-brown-elephant.sh
        container: qc.doc_ready-grey-shark
  QC.Lic:
    repos:
      github.com/inab/openEbench-frontend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-chocolate-markhor.sh
        container: qc.lic_woozy-rust-flamingo
  QC.Sty:
    repos:
      github.com/inab/openEbench-frontend hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-burgundy-labradoodle.sh
        container: qc.sty_shabby-gold-seahorse
      github.com/inab/openEbench-frontend jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-lime-mandrill.sh
        container: qc.sty_boozy-persimmon-bordeaux
      github.com/inab/openEbench-frontend stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-xanthic-dachshund.sh
        container: qc.sty_silly-alizarin-albatross
  QC.Ver:
    repos:
      github.com/inab/openEbench-frontend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-platinum-dog.sh
        container: qc.ver_tasty-red-starfish
timeout: 1800
