config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/inab/oeb_general_docs:
      branch: master
      repo: https://github.com/inab/oeb_general_docs
    github.com/inab/openEbench-frontend:
      branch: master
      repo: https://github.com/inab/openEbench-frontend
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/inab/openEbench-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-salmon-liger.sh
        container: qc.acc_lovely-cardinal-barracuda
  QC.Doc:
    repos:
      github.com/inab/oeb_general_docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-cornflower-bat.sh
        container: qc.doc_skanky-bistre-hummingbird
      github.com/inab/oeb_general_docs git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-peach-affenpinscher.sh
        container: qc.doc_stinky-ultramarine-mandrill
      github.com/inab/oeb_general_docs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-celadon-lemming.sh
        container: qc.doc_cozy-violet-argentino
      github.com/inab/oeb_general_docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-gamboge-tzu.sh
        container: qc.doc_sunny-puce-kingfisher
  QC.Lic:
    repos:
      github.com/inab/openEbench-frontend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-sapphire-lionfish.sh
        container: qc.lic_woolly-white-bird
  QC.Ver:
    repos:
      github.com/inab/openEbench-frontend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-xanthic-wolfhound.sh
        container: qc.ver_geeky-ivory-mongoose
timeout: 1800
