config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/inab/openEbench-frontend:
      branch: master
      repo: https://github.com/inab/openEbench-frontend
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/inab/openEbench-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-taupe-albatross.sh
        container: qc.acc_silly-olive-crab
  QC.Doc:
    repos:
      github.com/inab/openEbench-frontend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-pink-mastiff.sh
        container: qc.doc_stinky-sangria-rhinoceros
      github.com/inab/openEbench-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-magenta-gibbon.sh
        container: qc.doc_chummy-cinnamon-flamingo
      github.com/inab/openEbench-frontend markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-jade-stingray.sh
        container: qc.doc_skinny-red-harrier
  QC.Lic:
    repos:
      github.com/inab/openEbench-frontend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-white-lionfish.sh
        container: qc.lic_slaphappy-turquoise-moose
  QC.Sty:
    repos:
      github.com/inab/openEbench-frontend hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-grey-emu.sh
        container: qc.sty_flimsy-aquamarine-newt
      github.com/inab/openEbench-frontend jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-cinnabar-chinook.sh
        container: qc.sty_randy-xanthic-stingray
      github.com/inab/openEbench-frontend stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-salmon-sheep.sh
        container: qc.sty_pretty-magnolia-snail
  QC.Ver:
    repos:
      github.com/inab/openEbench-frontend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-rust-frog.sh
        container: qc.ver_ready-rose-cassowary
timeout: 1800
