config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/inab/openEbench-frontend:
      branch: master
      repo: https://github.com/inab/openEbench-frontend
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/inab/openEbench-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-bistre-centipede.sh
        container: qc.acc_greasy-purple-frigatebird
  QC.Doc:
    repos:
      github.com/inab/openEbench-frontend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-magenta-stingray.sh
        container: qc.doc_tacky-saffron-dunker
      github.com/inab/openEbench-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-platinum-okapi.sh
        container: qc.doc_chewy-green-gorilla
      github.com/inab/openEbench-frontend markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-seashell-gharial.sh
        container: qc.doc_droopy-heliotrope-yak
  QC.Lic:
    repos:
      github.com/inab/openEbench-frontend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-ruby-beagle.sh
        container: qc.lic_flaky-brown-dunker
  QC.Sty:
    repos:
      github.com/inab/openEbench-frontend hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-orchid-grasshopper.sh
        container: qc.sty_chummy-dandelion-bonobo
      github.com/inab/openEbench-frontend jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-buff-quoll.sh
        container: qc.sty_cheeky-yellow-akbash
      github.com/inab/openEbench-frontend stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-eggplant-otter.sh
        container: qc.sty_pasty-goldenrod-lemur
  QC.Ver:
    repos:
      github.com/inab/openEbench-frontend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-indigo-lobster.sh
        container: qc.ver_cheeky-seashell-quetzal
timeout: 1800
